### ISSUE TITLE
Build Error in bufflist

### ISSUE THREAD

**Issue by fwx5618177** [nflvic/sql_example#1]
It would throw error:

```bash
/Users/fengwenxuan/.cache/zig/p/12207e420873668f1eca53ed414eb249153668530ce6a5f09025901da0357f255004/src/bufflist.zig:164:46: error: expected type 'usize', found '@TypeOf(.{})'
        var wr = writeStream(list.writer(), .{});
```

**Comment by nflvic** [comment]
> It would throw error:
> 
> ```bash
> /Users/fengwenxuan/.cache/zig/p/12207e420873668f1eca53ed414eb249153668530ce6a5f09025901da0357f255004/src/bufflist.zig:164:46: error: expected type 'usize', found '@TypeOf(.{})'
>         var wr = writeStream(list.writer(), .{});
> ```

What version of zig are you using?.

**Comment by fwx5618177** [comment]
> > It would throw error:
> > 
> > ```bash
> > /Users/fengwenxuan/.cache/zig/p/12207e420873668f1eca53ed414eb249153668530ce6a5f09025901da0357f255004/src/bufflist.zig:164:46: error: expected type 'usize', found '@TypeOf(.{})'
> >         var wr = writeStream(list.writer(), .{});
> > ```
> 
> What version of zig are you using?. 

Currently, I use the latest version. But it always mentioned this error so if you have any methods to solve it, please let me know.

**Comment by nflvic** [comment]
> > > It would throw error:
> > > 
> > > ```bash
> > > /Users/fengwenxuan/.cache/zig/p/12207e420873668f1eca53ed414eb249153668530ce6a5f09025901da0357f255004/src/bufflist.zig:164:46: error: expected type 'usize', found '@TypeOf(.{})'
> > >         var wr = writeStream(list.writer(), .{});
> > > ```
> > 
> > What version of zig are you using?. 
> 
> Currently, I use the latest version 11. But it always mentioned this error so if you have any methods to solve it, please let me know.

I am sorry it works on latest 0.12.0

**Comment by fwx5618177** [comment]
> > > > It would throw error:
> > > > ```shell
> > > > /Users/fengwenxuan/.cache/zig/p/12207e420873668f1eca53ed414eb249153668530ce6a5f09025901da0357f255004/src/bufflist.zig:164:46: error: expected type 'usize', found '@TypeOf(.{})'
> > > >         var wr = writeStream(list.writer(), .{});
> > > > ```
> > > 
> > > 
> > > What version of zig are you using?.
> > 
> > 
> > Currently, I use the latest version 11. But it always mentioned this error so if you have any methods to solve it, please let me know.
> 
> I am sorry it works on latest 0.12.0

zig 0.12.0 not published, your mean is master branch?

**Comment by nflvic** [comment]
> > > > > It would throw error:
> > > > > ```shell
> > > > > /Users/fengwenxuan/.cache/zig/p/12207e420873668f1eca53ed414eb249153668530ce6a5f09025901da0357f255004/src/bufflist.zig:164:46: error: expected type 'usize', found '@TypeOf(.{})'
> > > > >         var wr = writeStream(list.writer(), .{});
> > > > > ```
> > > > 
> > > > 
> > > > What version of zig are you using?.
> > > 
> > > 
> > > Currently, I use the latest version 11. But it always mentioned this error so if you have any methods to solve it, please let me know.
> > 
> > I am sorry it works on latest 0.12.0
> 
> zig 0.12.0 not published, your mean is master branch?

This one https://ziglang.org/builds/zig-linux-x86_64-0.12.0-dev.3152+90c1a2c41.tar.xz
